version: "2"
services:
  mysql:
    build: ./mysql
    restart: always
  node:
    build: ./node
    ports:
      - "3000:3000"
    depends_on:
     - mysql
    environment:
     - DATABASE_HOST=mysql
     - DATABASE_USER=cercinfo
     - DATABASE_NAME=cercinfo
     - DATABASE_PASSWORD=CdafwanwjgcTEW7d
     - JWT_SECRET=uBqETJWeedLXFb4MY5KYV2Z8ecVSCxxC
    volumes:
      - ".:/src/app"
    restart: always
